export const COMPANIES = [
	{
		logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1200px-Google_%22G%22_Logo.svg.png",
		name: "Google",
		registrations: 32,
		ctc: 34,
		stipend: 34,
		profile: "SDE",
		offer: "P+I",
		isSpot: true,
		location: ["Bangalore", "Pune"],
		category: "CORE",
		dates: "27th Dec - 31st Dec",
		status: "PENDING",
	},
	{
		logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1200px-Google_%22G%22_Logo.svg.png",
		name: "Google",
		registrations: 32,
		ctc: 34,
		stipend: 34,
		profile: "SDE",
		offer: "P+I",
		isSpot: true,
		location: ["Bangalore", "Pune", "Delhi", "Chennai"],
		category: "CORE",
		dates: "27th Dec - 31st Dec",
		status: "PENDING",
	},
	{
		logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1200px-Google_%22G%22_Logo.svg.png",
		name: "Google",
		registrations: 32,
		ctc: 34,
		stipend: 34,
		profile: "SDE",
		offer: "P+I",
		isSpot: true,
		location: ["Bangalore", "Pune"],
		category: "CORE",
		dates: "27th Dec - 31st Dec",
		status: "PENDING",
	},
	{
		logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1200px-Google_%22G%22_Logo.svg.png",
		name: "Google",
		registrations: 32,
		ctc: 34,
		stipend: 34,
		profile: "SDE",
		offer: "P+I",
		isSpot: true,
		location: ["Bangalore", "Pune"],
		category: "CORE",
		dates: "27th Dec - 31st Dec",
		status: "PENDING",
	},
	{
		logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1200px-Google_%22G%22_Logo.svg.png",
		name: "Google",
		registrations: 32,
		ctc: 34,
		stipend: 34,
		profile: "SDE",
		offer: "P+I",
		isSpot: true,
		location: ["Bangalore", "Pune"],
		category: "CORE",
		dates: "27th Dec - 31st Dec",
		status: "CLOSED",
	},
	{
		logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1200px-Google_%22G%22_Logo.svg.png",
		name: "Google",
		registrations: 32,
		ctc: 34,
		stipend: 34,
		profile: "SDE",
		offer: "P+I",
		isSpot: false,
		location: ["Bangalore", "Pune"],
		category: "CORE",
		dates: "27th Dec - 31st Dec",
		status: "OPEN",
	},
	{
		logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1200px-Google_%22G%22_Logo.svg.png",
		name: "Google",
		registrations: 32,
		ctc: 34,
		stipend: 34,
		profile: "SDE",
		offer: "P+I",
		isSpot: true,
		location: ["Bangalore", "Pune"],
		category: "CORE",
		dates: "27th Dec - 31st Dec",
		status: "CLOSED",
	},
	{
		logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1200px-Google_%22G%22_Logo.svg.png",
		name: "Google",
		registrations: 32,
		ctc: 34,
		stipend: 34,
		profile: "SDE",
		offer: "P+I",
		isSpot: false,
		location: ["Bangalore", "Pune"],
		category: "CORE",
		dates: "27th Dec - 31st Dec",
		status: "OPEN",
	},
	{
		logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1200px-Google_%22G%22_Logo.svg.png",
		name: "Google",
		registrations: 32,
		ctc: 34,
		stipend: 34,
		profile: "SDE",
		offer: "P+I",
		isSpot: true,
		location: ["Bangalore", "Pune"],
		category: "CORE",
		dates: "27th Dec - 31st Dec",
		status: "CLOSED",
	},
	{
		logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1200px-Google_%22G%22_Logo.svg.png",
		name: "Google",
		registrations: 32,
		ctc: 34,
		stipend: 34,
		profile: "SDE",
		offer: "P+I",
		isSpot: false,
		location: ["Bangalore", "Pune"],
		category: "CORE",
		dates: "27th Dec - 31st Dec",
		status: "OPEN",
	},
	{
		logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1200px-Google_%22G%22_Logo.svg.png",
		name: "Google",
		registrations: 32,
		ctc: 34,
		stipend: 34,
		profile: "SDE",
		offer: "P+I",
		isSpot: true,
		location: ["Bangalore", "Pune"],
		category: "CORE",
		dates: "27th Dec - 31st Dec",
		status: "CLOSED",
	},
	{
		logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1200px-Google_%22G%22_Logo.svg.png",
		name: "Google",
		registrations: 32,
		ctc: 34,
		stipend: 34,
		profile: "SDE",
		offer: "P+I",
		isSpot: false,
		location: ["Bangalore", "Pune"],
		category: "CORE",
		dates: "27th Dec - 31st Dec",
		status: "OPEN",
	},
	{
		logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1200px-Google_%22G%22_Logo.svg.png",
		name: "Google",
		registrations: 32,
		ctc: 34,
		stipend: 34,
		profile: "SDE",
		offer: "P+I",
		isSpot: true,
		location: ["Bangalore", "Pune"],
		category: "CORE",
		dates: "27th Dec - 31st Dec",
		status: "PENDING",
	},
	{
		logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1200px-Google_%22G%22_Logo.svg.png",
		name: "Google",
		registrations: 32,
		ctc: 34,
		stipend: 34,
		profile: "SDE",
		offer: "P+I",
		isSpot: true,
		location: ["Bangalore", "Pune"],
		category: "CORE",
		dates: "27th Dec - 31st Dec",
		status: "CLOSED",
	},
	{
		logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1200px-Google_%22G%22_Logo.svg.png",
		name: "Google",
		registrations: 32,
		ctc: 34,
		stipend: 34,
		profile: "SDE",
		offer: "P+I",
		isSpot: false,
		location: ["Bangalore", "Pune"],
		category: "CORE",
		dates: "27th Dec - 31st Dec",
		status: "OPEN",
	},
];

export const TABLE_HEADERS = ["Company", "CTC", "Stipend", "Profile", "Offer", "Location", "Category", "Status"];
